# Generated by Django 5.1 on 2024-08-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_postit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="conteudo",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="card",
            name="detalhes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
