# Generated by Django 5.1 on 2024-11-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_postit", "0003_quadro_borda_cards_quadro_cor_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadro",
            name="coluna_data",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quadro",
            name="colunas_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
